name: Ronin Ecosystem Validator

on:
  pull_request_target:
    types: [closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  tds_check:
    name: "Ronin Buddy"
    uses: './.github/workflows/ci.yml'
    secrets: inherit